version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node-service

  node-service:
    build: ./api
    environment:
      NODE_ENV: production
    env_file:
      - .env
    depends_on:
      - db

  db:
    build: ./db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
